### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by darshannx** [aredwood/zonefile-parser#12]
[example.txt](https://github.com/aredwood/zonefile-parser/files/6297305/example.txt)

I had two questions but I'll start this one first. This is just an example of a zone file that I have but when I run it through the code example in the README. It gives back an error.

Error: 
  File "C:\python38\lib\site-packages\zonefile_parser\main.py", line 105, in parse
    normalized_records = list(
  File "C:\python38\lib\site-packages\zonefile_parser\main.py", line 107, in <lambda>
    lambda x : parse_record(x),
  File "C:\python38\lib\site-packages\zonefile_parser\parser.py", line 31, in parse_record
    "value":parts[RecordEnum.RDATA]
IndexError: list index out of range

This could possibly be an issue with the zone file as well because the package did work with another zone file example but that was a simpler one without a SOA entry

**Comment by aredwood** [comment]
resolved in #14

**Comment by darshannx** [comment]
so should I just update the package and I assume the issue will be fixed?

**Comment by darshannx** [comment]
just checked. Upgraded the package and it was fixed. Thanks!
