### ISSUE TITLE
IndexError: list index out of range - $ttl BIND9

### ISSUE THREAD

**Issue by artfulbodger** [aredwood/zonefile-parser#26]
Using example where the zone default TTL is set before the $ORIGIN (RFC2308):

$TTL 86400
$ORIGIN XX.EXAMPLE.
@       IN      SOA     NS1.XX.EXAMPLE. HOSTMATER.XX.EXAMPLE. (
                        1997102000      ; serial
                        1800    ; refresh (30 mins)
                        900     ; retry (15 mins)
                        604800  ; expire (7 days)
                        1200 ) ; minimum (20 mins)

Error:
Traceback (most recent call last):
  File "/code/zonefile_checker/./test.py", line 5, in <module>
    records = zonefile_parser.parse(content)
  File "/home/richc/.local/share/virtualenvs/zonefile_checker-ZEjbhtc0/lib/python3.9/site-packages/zonefile_parser/main.py", line 140, in parse
    normalized_records = list(
  File "/home/richc/.local/share/virtualenvs/zonefile_checker-ZEjbhtc0/lib/python3.9/site-packages/zonefile_parser/main.py", line 142, in <lambda>
    lambda x : parse_record(x),
  File "/home/richc/.local/share/virtualenvs/zonefile_checker-ZEjbhtc0/lib/python3.9/site-packages/zonefile_parser/parser.py", line 48, in parse_record
    parts[RecordEnum.RDATA]
IndexError: list index out of range

Removing $TTL 86400 from the first line does not produce the error.

**Comment by aredwood** [comment]
hey man, thanks for raising this - I can't actually reproduce this error - instead I get something else entirely. 

i've added your example as a test case and receive a different error, https://github.com/aredwood/zonefile-parser/actions/runs/4290795777/jobs/7475192413

the project also has test coverage for having the ttl before the origin https://github.com/aredwood/zonefile-parser/blob/master/zonefile_parser/main_test.py#L68

is the error in the CI run above the same one you're experiencing when you use the tool?

**Comment by artfulbodger** [comment]
hey @aredwood , I've managed to reproduce the error with the following in a zone file

$ttl 15M
example.com.	IN	SOA	NS1.XX.EXAMPLE. HOSTMATER.XX.EXAMPLE. (
			2023011802
			5M
			10M
			28D
			1H )
example.com.	IN	NS	ns0.XX.EXAMPLE.
example.com.	IN	NS	ns1.XX.EXAMPLE.
example.com.	IN	NS	ns2.XX.EXAMPLE.
live.example.com.	IN	NS	ns-2041.awsdns-63.co.uk.
live.example.com.	IN	NS	ns-482.awsdns-60.com.
live.example.com.	IN	NS	ns-1052.awsdns-03.org.
live.example.com.	IN	NS	ns-584.awsdns-09.net.
data.example.com.	IN	NS	ns-67.awsdns-08.com.
data.example.com.	IN	NS	ns-1858.awsdns-40.co.uk.
data.example.com.	IN	NS	ns-602.awsdns-11.net.
data.example.com.	IN	NS	ns-1234.awsdns-26.org.

It appears to be a case sensitivity issue with $ttl vs $TTL.  I don't get the error if I replace `$ttl` with `$TTL`

**Comment by aredwood** [comment]
@artfulbodger released in https://github.com/aredwood/zonefile-parser/releases/tag/0.1.14
