### ISSUE TITLE
ValueError: invalid literal for int()

### ISSUE THREAD

**Issue by ErnHem** [aredwood/zonefile-parser#7]
Hello,

First of all thanks for your work!

When I parsed my zone file I got this error

`ValueError: invalid literal for int() with base 10: '10m'`

This error is occurred within the function **default_ttl** 
```
def default_ttl(text:str):
    lines = text.splitlines()
    for line in lines:
        if "$TTL" in line:
            ttl = line.split(" ")[1]
            return int(ttl)
        return None
```

In my zone file, different TTL values are used, I mean 10s, 10m, 10h

Maybe change the returned value in a simple string? I mean `return ttl`

Or create a function that will translate these values (10s, 10m, 10h) in seconds?

BR

**Comment by aredwood** [comment]
i've been meaning to do that, I'll get on it.

**Comment by aredwood** [comment]
Sorted in release 0.1.5, published.
